/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnThisDayRouteImport } from './routes/on-this-day'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WriteRouteImport } from './routes/write'
import { Route as EntryDateRouteImport } from './routes/entry.$date'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as VolumePeriodKeyRouteImport } from './routes/volume.$periodKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnThisDayRoute = OnThisDayRouteImport.update({
  id: '/on-this-day',
  path: '/on-this-day',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryDateRoute = EntryDateRouteImport.update({
  id: '/entry/$date',
  path: '/entry/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumePeriodKeyRoute = VolumePeriodKeyRouteImport.update({
  id: '/volume/$periodKey',
  path: '/volume/$periodKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/on-this-day': typeof OnThisDayRoute
  '/settings': typeof SettingsRoute
  '/write': typeof WriteRoute
  '/entry/$date': typeof EntryDateRoute
  '/tag/$tag': typeof TagTagRoute
  '/volume/$periodKey': typeof VolumePeriodKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/on-this-day': typeof OnThisDayRoute
  '/settings': typeof SettingsRoute
  '/write': typeof WriteRoute
  '/entry/$date': typeof EntryDateRoute
  '/tag/$tag': typeof TagTagRoute
  '/volume/$periodKey': typeof VolumePeriodKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/on-this-day': typeof OnThisDayRoute
  '/settings': typeof SettingsRoute
  '/write': typeof WriteRoute
  '/entry/$date': typeof EntryDateRoute
  '/tag/$tag': typeof TagTagRoute
  '/volume/$periodKey': typeof VolumePeriodKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/dev-login'
    | '/login'
    | '/on-this-day'
    | '/settings'
    | '/write'
    | '/entry/$date'
    | '/tag/$tag'
    | '/volume/$periodKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/dev-login'
    | '/login'
    | '/on-this-day'
    | '/settings'
    | '/write'
    | '/entry/$date'
    | '/tag/$tag'
    | '/volume/$periodKey'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/dev-login'
    | '/login'
    | '/on-this-day'
    | '/settings'
    | '/write'
    | '/entry/$date'
    | '/tag/$tag'
    | '/volume/$periodKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  DevLoginRoute: typeof DevLoginRoute
  LoginRoute: typeof LoginRoute
  OnThisDayRoute: typeof OnThisDayRoute
  SettingsRoute: typeof SettingsRoute
  WriteRoute: typeof WriteRoute
  EntryDateRoute: typeof EntryDateRoute
  TagTagRoute: typeof TagTagRoute
  VolumePeriodKeyRoute: typeof VolumePeriodKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-this-day': {
      id: '/on-this-day'
      path: '/on-this-day'
      fullPath: '/on-this-day'
      preLoaderRoute: typeof OnThisDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$date': {
      id: '/entry/$date'
      path: '/entry/$date'
      fullPath: '/entry/$date'
      preLoaderRoute: typeof EntryDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$periodKey': {
      id: '/volume/$periodKey'
      path: '/volume/$periodKey'
      fullPath: '/volume/$periodKey'
      preLoaderRoute: typeof VolumePeriodKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  DevLoginRoute: DevLoginRoute,
  LoginRoute: LoginRoute,
  OnThisDayRoute: OnThisDayRoute,
  SettingsRoute: SettingsRoute,
  WriteRoute: WriteRoute,
  EntryDateRoute: EntryDateRoute,
  TagTagRoute: TagTagRoute,
  VolumePeriodKeyRoute: VolumePeriodKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
